# Generated by Django 2.1.11 on 2020-03-11 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cdis_app', '0002_auto_20200311_1715'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=13)),
                ('medical_rec_number', models.CharField(max_length=9)),
                ('admit_date', models.DateField()),
                ('discharge_date', models.DateField()),
                ('length_of_stay', models.IntegerField(default=1)),
                ('financial_class', models.CharField(max_length=50)),
                ('status', models.BooleanField(choices=[(True, 'Admitted'), (False, 'Discharged')])),
            ],
        ),
        migrations.AlterField(
            model_name='employee',
            name='username',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='cdis_app.Employee'),
        ),
    ]
