# Generated by Django 2.1.11 on 2020-03-11 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdis_app', '0003_auto_20200311_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='financial_class',
            field=models.CharField(choices=[('Aetna HMO', 'Aetna HMO'), ('Aetna POS', 'Aetna POS'), ('Aetna PPO', 'Aetna PPO'), ('Alliant Health Plans', 'Alliant Health Plans'), ('Amerigroup (Medicaid)', 'Amerigroup (Medicaid)'), ('Athens Area Health Plan', 'Athens Area Health Plan'), ('BCBS HMO', 'BCBS HMO'), ('BCBS POS', 'BCBS POS'), ('BCBS PPO', 'BCBS PPO'), ('Beech Street', 'Beech Street'), ('Care Source (Medicaid)', 'Care Source (Medicaid)'), ('Cigna HMO', 'Cigna HMO'), ('Cigna POS', 'Cigna POS'), ('Cigna PPO', 'Cigna PPO'), ('CorVel', 'CorVel'), ('Coventry Healthcare HMO', 'Coventry Healthcare HMO'), ('Coventry Healthcare POS', 'Coventry Healthcare POS'), ('Coventry Healthcare National Network PPO', 'Coventry Healthcare National Network PPO'), ('Crescent Health Solutions', 'Crescent Health Solutions'), ('FirstHealth PPO (Coventry Product)', 'FirstHealth PPO (Coventry Product)'), ('Galaxy Health Network', 'Galaxy Health Network'), ('Global Medical Management', 'Global Medical Management'), ('Health One Alliance', 'Health One Alliance'), ('Humana HMO', 'Humana HMO'), ('Humana POS', 'Humana POS'), ('Humana PPO', 'Humana PPO'), ('Industry Buying Group', 'Industry Buying Group'), ('Kaiser HMO', 'Kaiser HMO'), ('Kaiser POS', 'Kaiser POS'), ('Kaiser PPO', 'Kaiser PPO'), ('LifeWell Health Partners', 'LifeWell Health Partners'), ('Memorial Health Services', 'Memorial Health Services'), ('MultiPlan', 'MultiPlan'), ('Northeast Georgia Health Partners', 'Northeast Georgia Health Partners'), ('NovaNet', 'NovaNet'), ('Peach State Health Plan (Medicaid)', 'Peach State Health Plan (Medicaid)'), ('Private Health Care Systems(PHCS)', 'Private Health Care Systems(PHCS)'), ('State Health Benefit Plan', 'State Health Benefit Plan'), ('United Healthcare HMO', 'United Healthcare HMO'), ('United Healthcare POS', 'United Healthcare POS'), ('United Healthcare PPO', 'United Healthcare PPO'), ('USA Managed Care Organization', 'USA Managed Care Organization'), ('Walmart Emory ACO Health Plan', 'Walmart Emory ACO Health Plan'), ('WellCare (CMO Medicaid)', 'WellCare (CMO Medicaid)')], max_length=60),
        ),
    ]
