# Generated by Django 2.1.11 on 2020-03-11 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cdis_app', '0005_demographic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nursing_unit', models.CharField(max_length=8)),
                ('room', models.CharField(max_length=15)),
                ('date_in', models.DateField()),
                ('date_out', models.DateField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='cdis_app.Patient')),
            ],
        ),
    ]
