# Generated by Django 2.1.11 on 2020-03-12 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdis_app', '0006_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(max_length=60)),
                ('doctor_question', models.CharField(max_length=1000)),
                ('clinical_indicators', models.CharField(max_length=1000)),
                ('history_and_physical', models.CharField(max_length=1000)),
                ('treatment', models.CharField(max_length=1000)),
            ],
        ),
    ]
