# Generated by Django 2.1.11 on 2020-03-12 02:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cdis_app', '0007_query'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ep', models.CharField(max_length=500)),
                ('vs', models.CharField(max_length=500)),
                ('diagnostics', models.CharField(max_length=500)),
                ('mar', models.CharField(max_length=500)),
                ('pmh', models.CharField(max_length=500)),
                ('history_and_physical', models.CharField(max_length=500)),
                ('query_opportunities', models.CharField(max_length=500)),
                ('labs', models.CharField(choices=[('Review', 'Review'), ('Re-Review', 'Re-Review')], max_length=40)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient+', to='cdis_app.Patient')),
            ],
        ),
    ]
