# Generated by Django 2.1.11 on 2020-03-17 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdis_app', '0011_auto_20200315_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='type',
            field=models.CharField(choices=[('Review', 'Review'), ('Re-Review', 'Re-Review')], default='review', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patient',
            name='financial_class',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='patient',
            name='status',
            field=models.CharField(choices=[('Admitted', 'Admitted'), ('Discharged', 'Discharged')], max_length=30),
        ),
        migrations.AlterField(
            model_name='review',
            name='labs',
            field=models.CharField(max_length=500),
        ),
    ]
